/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ftpclient;

import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author pedja
 */
public class ServerConfiguration extends javax.swing.JFrame {

    private String IPAdresaServera;
    private int portServera;

    public String getIPAdresaServera() {
        return IPAdresaServera;
    }

    public void setIPAdresaServera(String IPAdresaServera) {
        this.IPAdresaServera = IPAdresaServera;
    }

    public int getPortServera() {
        return portServera;
    }

    public void setPortServera(int portServera) {
        this.portServera = portServera;
    }
    
    public void resetTextFields(){
        this.tfIPAdresaServera.setText("");
        this.tfPortServera.setText("");
    }
    /**
     * Creates new form ServerConfiguration
     */
    public ServerConfiguration() {
        initComponents();
        IPAdresaServera = null;
        portServera = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tfIPAdresaServera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPortServera = new javax.swing.JTextField();
        btnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Konfiguracija servera");

        jLabel1.setText("IP adresa servera:");

        jLabel2.setText("Port servera:");

        btnSacuvaj.setText("Sacuvaj");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSacuvaj)
                    .addComponent(tfIPAdresaServera, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfPortServera, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tfIPAdresaServera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPortServera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(btnSacuvaj)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed
        // TODO add your handling code here:
        //regex pattern za povrsno ispitivanje validnost unete IP adrese
        Pattern simplePatternIP = Pattern.compile("^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$");
        this.IPAdresaServera = this.tfIPAdresaServera.getText();
        if (simplePatternIP.matcher(IPAdresaServera).matches()) {
            try {
                this.portServera = Integer.parseInt(this.tfPortServera.getText());
                this.setVisible(false);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Morate uneti port servera!");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Morate uneti IP adresu servera!");
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfIPAdresaServera;
    private javax.swing.JTextField tfPortServera;
    // End of variables declaration//GEN-END:variables
}
